# Generated by Django 2.2.7 on 2021-03-04 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=32, verbose_name='学生姓名')),
            ],
            options={
                'db_table': 'grade_students',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=32, verbose_name='科目')),
                ('score', models.FloatField(default=0, verbose_name='分数')),
                ('sort', models.IntegerField(default=1, verbose_name='排名')),
                ('year', models.SmallIntegerField(verbose_name='年份')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_grade', to='grade.Student')),
            ],
            options={
                'db_table': 'grade',
            },
        ),
    ]
