# Generated by Django 2.2.7 on 2021-03-04 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='sort',
        ),
    ]
