# Generated by Django 2.2.7 on 2021-02-18 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_student_id_no'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
