# Generated by Django 2.2.7 on 2021-02-18 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_auto_20210218_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-updated_at']},
        ),
    ]
