# Generated by Django 2.2.7 on 2021-02-18 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_course'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
    ]
