# Generated by Django 2.2.7 on 2021-02-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0006_auto_20210218_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyStudent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('oauth.student',),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='oauth.Course'),
        ),
    ]
