# Generated by Django 2.2.7 on 2021-02-18 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0007_auto_20210218_1657'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='user',
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(max_length=256, verbose_name='用户签名')),
                ('isonline', models.IntegerField(choices=[('1', '是'), ('2', '否'), ('3', '离开'), ('4', '忙碌'), ('5', '隐身')], default='1', verbose_name='是否在线')),
                ('birthday', models.DateTimeField(verbose_name='生日')),
                ('bloodtype', models.IntegerField(choices=[('1', 'A'), ('2', 'B'), ('3', 'O'), ('4', 'AB'), ('5', '其他')], default='1', verbose_name='血型')),
                ('professional', models.TextField(max_length=256, verbose_name='职业')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oauth.Student')),
            ],
        ),
    ]
