# Generated by Django 2.2.7 on 2021-02-18 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0008_auto_20210218_1734'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdetail',
            table='user_detail',
        ),
    ]
