# Generated by Django 2.2.7 on 2021-02-20 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0002_auto_20210219_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weibo',
            options={'ordering': ['id']},
        ),
    ]
