# Generated by Django 2.2.7 on 2021-02-21 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0004_auto_20210220_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='weibouser',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weibouser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
    ]
