# Generated by Django 2.2.7 on 2021-02-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0005_auto_20210221_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibouser',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
    ]
