# Generated by Django 2.2.7 on 2021-02-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0006_auto_20210221_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibouser',
            name='updated_at',
            field=models.DateTimeField(verbose_name='最后修改时间'),
        ),
    ]
