# Generated by Django 2.2.7 on 2021-02-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0008_weibouser_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibouser',
            name='create_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='weibouser',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后修改时间'),
        ),
    ]
