# Generated by Django 2.2.7 on 2021-03-06 15:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0009_auto_20210222_1516'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='weibouser',
            managers=[
                ('users', django.db.models.manager.Manager()),
            ],
        ),
    ]
